from . import views
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('about/', views.about, name='about-page'),
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('', views.home, name="home-page"),
    path('login', views.login_page, name="login"),
    path('userlogin', views.login_user, name="login-user"),
    path('register-user', views.register_user, name="register-user"),
    path('forgot-password', views.forgot_password, name="forgot-password"),
    path('change-password', views.change_password_page, name="change-password-page"),
    path('change-password-login', views.change_password_login, name="change-password-login"),
    path('users', views.users_page, name="users-page"),
    path('toggle-user-role', views.toggle_user_role, name="toggle-user-role"),
    path('toggle-user-status', views.toggle_user_status, name="toggle-user-status"),
    path('update-user-account', views.update_user_account, name="update-user-account"),
    path('delete-user-account', views.delete_user_account, name="delete-user-account"),
    path('logout', views.logoutuser, name="logout"),
    path('category', views.category, name="category-page"),
    path('manage_category', views.manage_category, name="manage_category-page"),
    path('save_category', views.save_category, name="save-category-page"),
    path('delete_category', views.delete_category, name="delete-category"),
    path('customers', views.customers, name="customer-page"),
    path('manage_customer', views.manage_customer, name="manage_customer-page"),
    path('select_customer_modal', views.select_customer_modal, name="select-customer-modal"),
    path('save_customer', views.save_customer, name="save-customer-page"),
    path('delete_customer', views.delete_customer, name="delete-customer"),
    path('receivables', views.receivables_dashboard, name="receivables-page"),
    path('cash-closing', views.cash_closing, name="cash-closing-page"),
    path('management-reports', views.management_reports, name="management-reports-page"),
    path('suppliers', views.suppliers, name="suppliers-page"),
    path('manage_supplier', views.manage_supplier, name="manage-supplier-page"),
    path('save_supplier', views.save_supplier, name="save-supplier-page"),
    path('delete_supplier', views.delete_supplier, name="delete-supplier"),
    path('supplier-prices', views.supplier_prices, name="supplier-prices-page"),
    path('manage_supplier_price', views.manage_supplier_price, name="manage-supplier-price-page"),
    path('save_supplier_price', views.save_supplier_price, name="save-supplier-price-page"),
    path('delete_supplier_price', views.delete_supplier_price, name="delete-supplier-price"),
    path('manage_supplier_product_create', views.manage_supplier_product_create, name="manage-supplier-product-create"),
    path('save_supplier_product_create', views.save_supplier_product_create, name="save-supplier-product-create"),
    path('reminders-accounts', views.reminders_accounts, name="reminders-accounts-page"),
    path('manage_payable_account', views.manage_payable_account, name="manage-payable-account-page"),
    path('save_payable_account', views.save_payable_account, name="save-payable-account-page"),
    path('delete_payable_account', views.delete_payable_account, name="delete-payable-account"),
    path('manage_finance_reminder', views.manage_finance_reminder, name="manage-finance-reminder-page"),
    path('save_finance_reminder', views.save_finance_reminder, name="save-finance-reminder-page"),
    path('delete_finance_reminder', views.delete_finance_reminder, name="delete-finance-reminder"),
    path('products', views.products, name="product-page"),
    path('manage_product', views.manage_product, name="manage_product-page"),
    path('test', views.test, name="test-page"),
    path('save_product', views.save_product, name="save-product-page"),
    path('delete_product', views.delete_product, name="delete-product"),
    path('pos', views.pos, name="pos-page"),
    path('checkout-modal', views.checkout_modal, name="checkout-modal"),
    path('save-pos', views.save_pos, name="save-pos"),
    path('sales', views.salesList, name="sales-page"),
    path('receipt', views.receipt, name="receipt-modal"),
    path('delete_sale', views.delete_sale, name="delete-sale"),
    path('generate-sales-report', views.generate_sales_report, name="generate-sales-report"),

]