# Generated by Django 5.1.7 on 2026-03-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorys',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
