# Generated by Django 5.2.6 on 2026-05-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0010_sales_comanda_discount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='comanda_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
