# Generated by Django 5.1.7 on 2026-05-21 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0012_customers_sales_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('reminder_type', models.CharField(choices=[('RECEIVABLE', 'Receber'), ('PAYABLE', 'Pagar'), ('GENERAL', 'Geral')], default='GENERAL', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DONE', 'Concluido')], default='PENDING', max_length=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reminders', to='conveniencia_bobesponjaApp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='PayableAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180)),
                ('amount', models.FloatField(default=0)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Em aberto'), ('PAID', 'Pago'), ('OVERDUE', 'Atrasado')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='conveniencia_bobesponjaApp.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProductPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=160)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='conveniencia_bobesponjaApp.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='conveniencia_bobesponjaApp.suppliers')),
            ],
            options={
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
