# Generated by Django 5.2.6 on 2026-05-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0013_suppliers_financereminders_payableaccounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprices',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplierproductprices',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
