# Generated by Django 5.1.7 on 2026-05-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0014_supplierproductprices_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='qty_baixada',
            field=models.IntegerField(default=0),
        ),
    ]
