# Generated by Django 5.2.6 on 2026-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0014_supplierproductprices_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='submission_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
