# Generated by Django 5.2.6 on 2026-06-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0015_categorys_submission_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='submission_key',
        ),
        migrations.AddField(
            model_name='financereminders',
            name='submission_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
