# Generated by Django 5.2.6 on 2026-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conveniencia_bobesponjaApp', '0017_remove_financereminders_submission_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='submission_key',
        ),
    ]
